# Generated by Django 4.0.6 on 2022-08-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='music',
            name='duration',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
