# Generated by Django 4.0.6 on 2022-08-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_music_photo_alter_music_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='author',
        ),
        migrations.AddField(
            model_name='music',
            name='author',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='music',
            name='created_at',
            field=models.DateField(),
        ),
    ]
