# Generated by Django 4.0.6 on 2022-08-11 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('song', '0004_rename_music_song_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='product',
            new_name='song',
        ),
        migrations.AlterField(
            model_name='like',
            name='like',
            field=models.BooleanField(default=True, verbose_name='like'),
        ),
        migrations.AlterField(
            model_name='song',
            name='photo',
            field=models.ImageField(blank=True, upload_to='songs'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='song.song', verbose_name='images')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='comments')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='song.song')),
            ],
        ),
    ]
