# Generated by Django 4.0.6 on 2022-08-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0006_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='audio',
            field=models.FileField(default=1, upload_to='songs'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='song',
            table='Audio_store',
        ),
    ]
