# Generated by Django 4.0.6 on 2022-08-11 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0007_song_audio_alter_song_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='song',
            table='song',
        ),
    ]
