# Generated by Django 4.0.6 on 2022-08-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0008_alter_song_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='author',
            new_name='album',
        ),
        migrations.RemoveField(
            model_name='song',
            name='description',
        ),
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
