# Generated by Django 4.0.6 on 2022-08-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0013_song_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.CharField(max_length=20),
        ),
    ]
