# Generated by Django 4.0.6 on 2022-08-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0014_alter_song_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='audio',
            new_name='audio_file',
        ),
        migrations.AddField(
            model_name='song',
            name='audio_link',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
