# Generated by Django 4.0.6 on 2022-08-14 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0015_rename_audio_song_audio_file_song_audio_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
    ]
